modLoader="javafml"
loaderVersion="[43,)"
license="Unlicense"
[[mods]]
modId="blahaj"
version="${file.jarVersion}"
displayName="Bl√•haj - Reforged"
displayURL="https://modrinth.com/mod/blahaj-reforged"
logoFile="icon.png"
credits="Made by Hibi"
authors="Made by Hibi, ported to Forge by agnor99"

description='''
Soft toy, shark mod, 16px.
'''
[[dependencies.blahaj]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blahaj]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
